Python 3.13.5 (tags/v3.13.5:6cb20a2, Jun 11 2025, 16:15:46) [MSC v.1943 64 bit (AMD64)] on win32
Enter "help" below or click "Help" above for more information.

================ RESTART: C:/Users/MD SIFAT/Desktop/hospital.py ================

================ RESTART: C:/Users/MD SIFAT/Desktop/hospital.py ================
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:/Users/MD SIFAT/Desktop/hospital.py", line 92, in print_invoice
    f.write(invoice_text)
    ~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\MD SIFAT\AppData\Local\Programs\Python\Python313\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\u09f3' in position 158: character maps to <undefined>
>>> 
================ RESTART: C:/Users/MD SIFAT/Desktop/hospital.py ================
